
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Meeraj
 */
public class ConfirmOrder extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmOrder
     */
    int x,y;
    public ConfirmOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_MOP = new javax.swing.ButtonGroup();
        jPanel_PlaceOrder_Bar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ep_uid = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel_TOTAL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        jRadioButton_POD = new javax.swing.JRadioButton();
        jRadioButtonCard = new javax.swing.JRadioButton();
        jRadioButton_UPI = new javax.swing.JRadioButton();
        jTextField_cardN = new javax.swing.JTextField();
        jTextField_UPI = new javax.swing.JTextField();
        jTextField_MM = new javax.swing.JTextField();
        jTextField_YY = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton_next = new javax.swing.JButton();
        jTextField_CVV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jLabel_total = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_pm = new javax.swing.JLabel();
        jLabel_CUPI = new javax.swing.JLabel();
        jLabel_cupi = new javax.swing.JLabel();
        jLabel_O_ID = new javax.swing.JLabel();
        jButton_Cancel = new javax.swing.JButton();
        jButton_nextC = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_PlaceOrder_Bar.setBackground(new java.awt.Color(58, 134, 255));
        jPanel_PlaceOrder_Bar.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_PlaceOrder_Bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_PlaceOrder_BarMouseDragged(evt);
            }
        });
        jPanel_PlaceOrder_Bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_PlaceOrder_BarMousePressed(evt);
            }
        });
        jPanel_PlaceOrder_Bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Place Order");
        jPanel_PlaceOrder_Bar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel_PlaceOrder_Bar.add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        jLabel_Close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Close.setText(" X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });
        jPanel_PlaceOrder_Bar.add(jLabel_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 29, 29));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("ID:");
        jPanel_PlaceOrder_Bar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        ep_uid.setForeground(new java.awt.Color(204, 255, 255));
        ep_uid.setText("000");
        jPanel_PlaceOrder_Bar.add(ep_uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 20));

        jTabbedPane2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(474, 490));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Mode Of Payment");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel36.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Shipping Address:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 150, 30));

        jLabel_TOTAL.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jLabel_TOTAL.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TOTAL.setText("00000");
        jPanel2.add(jLabel_TOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 60, 20));

        jTextArea_Address.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea_Address.setColumns(20);
        jTextArea_Address.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Address);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 290, 130));

        jLabel37.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("TOTAL:₹");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, 20));

        buttonGroup_MOP.add(jRadioButton_POD);
        jRadioButton_POD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton_POD.setForeground(new java.awt.Color(51, 255, 0));
        jRadioButton_POD.setText("Pay On Delivery");
        jPanel2.add(jRadioButton_POD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        buttonGroup_MOP.add(jRadioButtonCard);
        jRadioButtonCard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonCard.setForeground(new java.awt.Color(51, 255, 0));
        jRadioButtonCard.setText("Credid/Debit card");
        jPanel2.add(jRadioButtonCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        buttonGroup_MOP.add(jRadioButton_UPI);
        jRadioButton_UPI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton_UPI.setForeground(new java.awt.Color(51, 255, 0));
        jRadioButton_UPI.setText("UPI");
        jPanel2.add(jRadioButton_UPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        jTextField_cardN.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextField_cardN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 220, -1));

        jTextField_UPI.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextField_UPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 220, -1));

        jTextField_MM.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextField_MM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 40, -1));

        jTextField_YY.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextField_YY, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 40, -1));

        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("Card Number");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setText("MM");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setText("YY");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 204, 204));
        jLabel7.setText("UPI ID :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 204, 204));
        jLabel8.setText("CVV code");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        jButton_next.setBackground(new java.awt.Color(255, 204, 0));
        jButton_next.setText("Next");
        jButton_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 100, 30));

        jTextField_CVV.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextField_CVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 70, -1));

        jLabel9.setForeground(new java.awt.Color(255, 204, 204));
        jLabel9.setText("Expiry Date :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jTabbedPane2.addTab("tab1", jPanel2);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        cartTable.setBackground(new java.awt.Color(0, 0, 0));
        cartTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cartTable.setForeground(new java.awt.Color(255, 255, 255));
        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S. No:", "Date and time", "cart ID", "food name", "quantity", "price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cartTable.setGridColor(new java.awt.Color(255, 0, 0));
        jScrollPane2.setViewportView(cartTable);
        if (cartTable.getColumnModel().getColumnCount() > 0) {
            cartTable.getColumnModel().getColumn(0).setPreferredWidth(3);
            cartTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            cartTable.getColumnModel().getColumn(2).setPreferredWidth(3);
            cartTable.getColumnModel().getColumn(3).setPreferredWidth(250);
            cartTable.getColumnModel().getColumn(4).setPreferredWidth(5);
            cartTable.getColumnModel().getColumn(5).setPreferredWidth(5);
            cartTable.getColumnModel().getColumn(6).setPreferredWidth(5);
        }

        jLabel_total.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jLabel_total.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_total.setText("00000");

        jLabel38.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("TOTAL:₹");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 0));
        jLabel10.setText("Mode Of Payment");

        jLabel_pm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_pm.setForeground(new java.awt.Color(0, 255, 51));
        jLabel_pm.setText("aaaaaaaaaaaaaaaa");

        jLabel_CUPI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_CUPI.setForeground(new java.awt.Color(255, 204, 204));
        jLabel_CUPI.setText("aaaa  aa:");

        jLabel_cupi.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel_cupi.setForeground(new java.awt.Color(255, 255, 0));
        jLabel_cupi.setText("xxxx xxxx xxxx xxxx");

        jLabel_O_ID.setForeground(new java.awt.Color(204, 255, 204));
        jLabel_O_ID.setText("1111");

        jButton_Cancel.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jButton_nextC.setBackground(new java.awt.Color(51, 255, 0));
        jButton_nextC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_nextC.setForeground(new java.awt.Color(255, 255, 255));
        jButton_nextC.setText("Confirm");
        jButton_nextC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_nextC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextCActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Order ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton_Cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_nextC)
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_O_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel_pm, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel_CUPI, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_cupi, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel_pm)
                    .addComponent(jLabel_CUPI)
                    .addComponent(jLabel_cupi))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_O_ID)
                    .addComponent(jLabel11))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancel)
                    .addComponent(jButton_nextC))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab2", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_PlaceOrder_Bar, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_PlaceOrder_Bar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 587, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 20, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void update_carttable(){
        try {
            PreparedStatement ps;
        ResultSet rs;
        String U_id = ep_uid.getText();
        
        String query = "SELECT * FROM `cart_list` WHERE `u_id` =?";
        
            ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, U_id);
            
            rs = ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)cartTable.getModel();
            tm.setRowCount(0);
            int i=1;
            while(rs.next())
            {
                    Object o[]={i,rs.getString(3),rs.getString(1),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
                    tm.addRow(o);
                    i++;
            }
                jLabel_total.setText("");
                int sum=0;
                for(int j=0;j<cartTable.getRowCount();j++){
                    sum+=Integer.parseInt(cartTable.getValueAt(j, 6).toString());
                }
                jLabel_TOTAL.setText(Integer.toString(sum));
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public  boolean valid_Card(String card){
        if(jTextField_MM.getText().isEmpty()){
            return false;
        }
        else if(jTextField_YY.getText().isEmpty()){
            return false;
        }
        else if(jTextField_CVV.getText().isEmpty()){
            return false;
        }
        else{
        int mm=Integer.parseInt(jTextField_MM.getText().toString());
        int yy=Integer.parseInt(jTextField_YY.getText().toString());
        int cvv=Integer.parseInt(jTextField_CVV.getText().toString());
        String Card= "^[0-9]{16}";
        Pattern cardPat=Pattern.compile(Card,Pattern.CASE_INSENSITIVE);
        Matcher mat=cardPat.matcher(card);
        if(mat.find()&&(mm<=31&&mm>0)&&(yy<=65&&yy>0)&&(cvv<=999&&cvv>0)){
            return true;
        }
        else{
        return false;
        }
        }
    }
    public boolean validUPI(String upi){
        String upiFormat= "^[a-zA-Z0-9.\\-_]{2,256}@[a-zA-Z]{2,64}$";
        Pattern upiPat=Pattern.compile(upiFormat);
        Matcher mat=upiPat.matcher(upi);
        return mat.find();
    }
    
    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jPanel_PlaceOrder_BarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_PlaceOrder_BarMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel_PlaceOrder_BarMouseDragged

    private void jPanel_PlaceOrder_BarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_PlaceOrder_BarMousePressed
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jPanel_PlaceOrder_BarMousePressed

    private void jButton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextActionPerformed
         String Add=jTextArea_Address.getText();
         String cn=jTextField_cardN.getText();
         String upi=jTextField_UPI.getText();
         String pm;
        if(jRadioButton_POD.isSelected()==false&&jRadioButtonCard.isSelected()==false&&jRadioButton_UPI.isSelected()==false){
            JOptionPane.showMessageDialog(null, "!!Select any one payment method!!");
        }
        else if(Add.isEmpty()){
                JOptionPane.showMessageDialog(null, "!!Your Shipping Address is empty!!");
                }
        else if(jRadioButtonCard.isSelected()&&(valid_Card(cn)==false)){
            JOptionPane.showMessageDialog(null, "!!Check your Card Details!!"); 
        }
        else if(jRadioButton_UPI.isSelected()&&(validUPI(upi)==false)){
            JOptionPane.showMessageDialog(null, "!!Your Entered wrong UPI ID!!\nEnter correct one");
        }
        else{
            jTabbedPane2.setSelectedIndex(1);
            update_carttable();
            jLabel_total.setText(jLabel_TOTAL.getText());
            if(jRadioButton_POD.isSelected()){
                jLabel_pm.setText("Pay On Delivery");
                jLabel_CUPI.setText("");
                jLabel_cupi.setText("");
                pm="Pay On Delivery";
            }
            else if(jRadioButtonCard.isSelected()){
                char[] cc = new char[4];
                String cl=jTextField_cardN.getText();
                cl.getChars(12, 16, cc, 0);
                String C=new String(cc);
                String c="xxxx xxxx xxxx "+C;
                jLabel_pm.setText("Credit/Debit Card");
                jLabel_CUPI.setText("Card no:");
                jLabel_cupi.setText(c);
                pm="Credit/Debit Card("+c+")";
            }
            else {
                jLabel_pm.setText("UPI");
                jLabel_CUPI.setText("UPI ID:");
                jLabel_cupi.setText(jTextField_UPI.getText());
                pm="UPI("+jTextField_UPI.getText()+")";
            }
                String items=(Integer.toString(cartTable.getRowCount()))+" items"; 
                String total=jLabel_TOTAL.getText();
               PreparedStatement ps;
        String query = "INSERT INTO `order_list`( `u_id`, `items`, `address`, `mod_pay`, `total`) VALUES (?,?,?,?,?)";
           ResultSet rs;
            try {
                ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
                
                ps.setString(1, ep_uid.getText());
                ps.setString(2, items);
                ps.setString(3, Add);
                ps.setString(4, pm);
                ps.setString(5, total);
                
                if(ps.executeUpdate() > 0)
                {
                    rs=ps.getGeneratedKeys();
                    if(rs.next()){
                        String id=rs.getString(1);
                        jLabel_O_ID.setText(id);
                    }
                    jLabelMin.setVisible(false);
                    jLabel_Close.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Dont Exit at this stage\n You can cancel this process by pressing cancel button", "Error", 2);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Somthing went wrong", "Error",2);
                }
                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        }
    }//GEN-LAST:event_jButton_nextActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        try {
            PreparedStatement ps;
            String query = "DELETE FROM `order_list` WHERE `o_id` ="+jLabel_O_ID.getText();
            ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Process cancelled sucessfully ");
            this.dispose();
            } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_nextCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextCActionPerformed
        for (int i = 0; i < cartTable.getRowCount(); i++) {
            String n=cartTable.getValueAt(i, 3).toString();
            String q=cartTable.getValueAt(i, 4).toString();
            String p=cartTable.getValueAt(i, 5).toString();
            String t=cartTable.getValueAt(i, 6).toString();
            PreparedStatement ps;
        String query = "INSERT INTO `order_items_list`(`o_id`, `u_id`, `food_name`, `quantity`, `price`, `total`) VALUES (?,?,?,?,?,?)";
            
            try {
                ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, jLabel_O_ID.getText());
                ps.setString(2, ep_uid.getText());
                ps.setString(3, n);
                ps.setString(4, q);
                ps.setString(5, p);
                ps.setString(6, t);
                
                if(ps.executeUpdate() > 0)
                {
                    
                }
                else{
                    JOptionPane.showMessageDialog(null,"Somthing went wrong", "Error",2);
                    return;
                }
                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        remove();
        Icon icon=new javax.swing.ImageIcon(getClass().getResource("/icons/success.png"));
            JOptionPane.showMessageDialog(null,"Order Placed Sucessfully\n✌Thanks for Shopping✌\n🌸Have a nice Day🌸", "!!Order Placed!!", JOptionPane.INFORMATION_MESSAGE,icon);
            update_carttable();
            this.dispose();
    }//GEN-LAST:event_jButton_nextCActionPerformed

    public void remove(){
        try {
            PreparedStatement ps1;
        
            String query1 = "DELETE FROM `cart_list` WHERE `u_id` ="+ep_uid.getText();
            ps1 = (PreparedStatement) MyConnection.getConnection().prepareStatement(query1);
            ps1.execute();
            } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_MOP;
    private javax.swing.JTable cartTable;
    protected javax.swing.JLabel ep_uid;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_next;
    private javax.swing.JButton jButton_nextC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabel_CUPI;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_O_ID;
    protected javax.swing.JLabel jLabel_TOTAL;
    private javax.swing.JLabel jLabel_cupi;
    private javax.swing.JLabel jLabel_pm;
    protected javax.swing.JLabel jLabel_total;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_PlaceOrder_Bar;
    private javax.swing.JRadioButton jRadioButtonCard;
    private javax.swing.JRadioButton jRadioButton_POD;
    private javax.swing.JRadioButton jRadioButton_UPI;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    protected javax.swing.JTextArea jTextArea_Address;
    private javax.swing.JTextField jTextField_CVV;
    private javax.swing.JTextField jTextField_MM;
    private javax.swing.JTextField jTextField_UPI;
    private javax.swing.JTextField jTextField_YY;
    private javax.swing.JTextField jTextField_cardN;
    // End of variables declaration//GEN-END:variables
}
