import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Meeraj
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        ByCatogory1.setVisible(false);
        ByHotel1.setVisible(false);
    }
    int x,y;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        HomeBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Navigation = new javax.swing.JPanel();
        Profile = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Cart = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Orders = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        About = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Home = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ByCatogory = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ByHotel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel93 = new javax.swing.JPanel();
        jLabel402 = new javax.swing.JLabel();
        jLabel403 = new javax.swing.JLabel();
        h56n = new javax.swing.JLabel();
        h56q = new javax.swing.JSpinner();
        jLabel405 = new javax.swing.JLabel();
        h56p = new javax.swing.JLabel();
        h56 = new javax.swing.JButton();
        jPanel69 = new javax.swing.JPanel();
        jLabel299 = new javax.swing.JLabel();
        jLabel300 = new javax.swing.JLabel();
        h21n = new javax.swing.JLabel();
        h21q = new javax.swing.JSpinner();
        jLabel302 = new javax.swing.JLabel();
        h21p = new javax.swing.JLabel();
        h21 = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        h312n = new javax.swing.JLabel();
        h312q = new javax.swing.JSpinner();
        jLabel146 = new javax.swing.JLabel();
        h312p = new javax.swing.JLabel();
        h312 = new javax.swing.JButton();
        jLabel67 = new javax.swing.JLabel();
        ByHotel1 = new javax.swing.JPanel();
        ByCatogory1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel_Profile = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        bdate = new javax.swing.JLabel();
        jButton_editProfile = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jPanel_Cart = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton_placeOrder = new javax.swing.JButton();
        jLabel_TOTAL = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel_fn = new javax.swing.JLabel();
        jLabel_foodName = new javax.swing.JLabel();
        jLabel_q = new javax.swing.JLabel();
        jLabel_quantity = new javax.swing.JLabel();
        jLabel_p = new javax.swing.JLabel();
        jLabel_t = new javax.swing.JLabel();
        jLabel_price = new javax.swing.JLabel();
        jLabel_total = new javax.swing.JLabel();
        jButton_remove = new javax.swing.JButton();
        jLabel_Cid = new javax.swing.JLabel();
        jLabel_cid = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton_change = new javax.swing.JButton();
        jSpinner_Q = new javax.swing.JSpinner();
        jPanel_Order = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        jPanel_About = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        jLabel_twitter = new javax.swing.JLabel();
        jLabel_facebook = new javax.swing.JLabel();
        jLabel_instagram = new javax.swing.JLabel();
        jPanel_OrderItems = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        BackButton_OL = new javax.swing.JLabel();
        jLabel_OID = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_OrderList = new javax.swing.JTable();
        jLabel_Ototal = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 680));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeBar.setBackground(new java.awt.Color(51, 153, 255));
        HomeBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HomeBarMouseDragged(evt);
            }
        });
        HomeBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeBarMousePressed(evt);
            }
        });
        HomeBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FOODZ");
        HomeBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 46, 180, 50));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        HomeBar.add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        HomeBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 20, -1));

        jPanel1.add(HomeBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 120));

        Navigation.setBackground(new java.awt.Color(102, 102, 102));
        Navigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Profile.setBackground(new java.awt.Color(102, 102, 102));
        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_mouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Profile");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_profileIcon.png"))); // NOI18N

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Navigation.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 241, 210, -1));

        Cart.setBackground(new java.awt.Color(102, 102, 102));
        Cart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_mouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cart list ");

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping-cart.png"))); // NOI18N

        javax.swing.GroupLayout CartLayout = new javax.swing.GroupLayout(Cart);
        Cart.setLayout(CartLayout);
        CartLayout.setHorizontalGroup(
            CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        CartLayout.setVerticalGroup(
            CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CartLayout.createSequentialGroup()
                .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Navigation.add(Cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 289, 210, -1));

        Orders.setBackground(new java.awt.Color(102, 102, 102));
        Orders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_mouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Your Orders");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/confirm.png"))); // NOI18N

        javax.swing.GroupLayout OrdersLayout = new javax.swing.GroupLayout(Orders);
        Orders.setLayout(OrdersLayout);
        OrdersLayout.setHorizontalGroup(
            OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdersLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(19, 19, 19))
        );
        OrdersLayout.setVerticalGroup(
            OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdersLayout.createSequentialGroup()
                .addGroup(OrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Navigation.add(Orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 337, 210, -1));

        About.setBackground(new java.awt.Color(102, 102, 102));
        About.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_mouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("About");

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/qa.png"))); // NOI18N

        javax.swing.GroupLayout AboutLayout = new javax.swing.GroupLayout(About);
        About.setLayout(AboutLayout);
        AboutLayout.setHorizontalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        AboutLayout.setVerticalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutLayout.createSequentialGroup()
                .addGroup(AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Navigation.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 385, 210, -1));

        Logout.setBackground(new java.awt.Color(102, 102, 102));
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                N_mouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LOGOUT");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout (1).png"))); // NOI18N

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutLayout.createSequentialGroup()
                .addGroup(LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        Navigation.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 433, 210, -1));

        Home.setBackground(new java.awt.Color(102, 102, 102));
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_mouseEnterd(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_mouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/homepage.png"))); // NOI18N

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Navigation.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Customer ID:");
        Navigation.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, -1, -1));

        id.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(0, 204, 204));
        id.setText("0000");
        Navigation.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 102, 72, -1));

        jPanel1.add(Navigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 570));

        jTabbedPane1.setBackground(new java.awt.Color(241, 250, 238));

        jPanel_Home.setBackground(new java.awt.Color(240, 239, 235));
        jPanel_Home.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hiclipart.com (20%).png"))); // NOI18N
        jPanel_Home.add(jLabel11);
        jLabel11.setBounds(30, 90, 60, 60);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hiclipart.com(25%).png"))); // NOI18N
        jPanel_Home.add(jLabel26);
        jLabel26.setBounds(360, 100, 60, 50);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hiclipart.com (50%).png"))); // NOI18N
        jPanel_Home.add(jLabel27);
        jLabel27.setBounds(700, 90, 70, 70);

        ByCatogory.setBackground(new java.awt.Color(102,102,102,160));
        ByCatogory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ByCatogory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ByCatogoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ByCatogoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ByCatogoryMouseExited(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Order");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("By");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Category");

        javax.swing.GroupLayout ByCatogoryLayout = new javax.swing.GroupLayout(ByCatogory);
        ByCatogory.setLayout(ByCatogoryLayout);
        ByCatogoryLayout.setHorizontalGroup(
            ByCatogoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ByCatogoryLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(ByCatogoryLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel23)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ByCatogoryLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ByCatogoryLayout.setVerticalGroup(
            ByCatogoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ByCatogoryLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel_Home.add(ByCatogory);
        ByCatogory.setBounds(560, 330, 270, 240);

        ByHotel.setBackground(new java.awt.Color(102,102,102,160));
        ByHotel.setForeground(new java.awt.Color(255, 255, 255));
        ByHotel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ByHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ByHotelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ByHotelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ByHotelMouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nearby");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Restaurants");

        javax.swing.GroupLayout ByHotelLayout = new javax.swing.GroupLayout(ByHotel);
        ByHotel.setLayout(ByHotelLayout);
        ByHotelLayout.setHorizontalGroup(
            ByHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ByHotelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel18)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ByHotelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        ByHotelLayout.setVerticalGroup(
            ByHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ByHotelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel_Home.add(ByHotel);
        ByHotel.setBounds(130, 330, 280, 240);

        jPanel93.setBackground(new java.awt.Color(0, 0, 0,130));
        jPanel93.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel402.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tandoori chicken and fish tikka and chilli chicken dry(1).jpeg"))); // NOI18N
        jPanel93.add(jLabel402, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel403.setForeground(new java.awt.Color(255, 204, 51));
        jLabel403.setText("Quantity");
        jPanel93.add(jLabel403, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 50, 20));

        h56n.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        h56n.setForeground(new java.awt.Color(51, 255, 204));
        h56n.setText("Chicken Tikka-Boneless");
        jPanel93.add(h56n, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, -1));

        h56q.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel93.add(h56q, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 30));

        jLabel405.setBackground(new java.awt.Color(255, 255, 0));
        jLabel405.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel405.setForeground(new java.awt.Color(255, 255, 0));
        jLabel405.setText("₹");
        jPanel93.add(jLabel405, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 10, -1));

        h56p.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        h56p.setForeground(new java.awt.Color(255, 255, 0));
        h56p.setText("129");
        jPanel93.add(h56p, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        h56.setBackground(new java.awt.Color(255, 102, 0));
        h56.setForeground(new java.awt.Color(255, 255, 255));
        h56.setText("Add to Cart");
        h56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h56ActionPerformed(evt);
            }
        });
        jPanel93.add(h56, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 150, 90, -1));

        jPanel_Home.add(jPanel93);
        jPanel93.setBounds(730, 120, 230, 190);

        jPanel69.setBackground(new java.awt.Color(0, 0, 0,130));
        jPanel69.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel299.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/margherita.jpeg"))); // NOI18N
        jPanel69.add(jLabel299, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel300.setForeground(new java.awt.Color(255, 204, 51));
        jLabel300.setText("Quantity");
        jPanel69.add(jLabel300, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 50, 20));

        h21n.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        h21n.setForeground(new java.awt.Color(51, 255, 204));
        h21n.setText("Margherita pizza");
        jPanel69.add(h21n, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 130, -1));

        h21q.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel69.add(h21q, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 30));

        jLabel302.setBackground(new java.awt.Color(255, 255, 0));
        jLabel302.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel302.setForeground(new java.awt.Color(255, 255, 0));
        jLabel302.setText("₹");
        jPanel69.add(jLabel302, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 10, -1));

        h21p.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        h21p.setForeground(new java.awt.Color(255, 255, 0));
        h21p.setText("199");
        jPanel69.add(h21p, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        h21.setBackground(new java.awt.Color(255, 102, 0));
        h21.setForeground(new java.awt.Color(255, 255, 255));
        h21.setText("Add to Cart");
        h21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h21ActionPerformed(evt);
            }
        });
        jPanel69.add(h21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jPanel_Home.add(jPanel69);
        jPanel69.setBounds(390, 120, 230, 190);

        jPanel36.setBackground(new java.awt.Color(0, 0, 0,130));

        jLabel143.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/schezwan-paneer-noodles.jpg"))); // NOI18N

        jLabel144.setForeground(new java.awt.Color(255, 204, 51));
        jLabel144.setText("Quantity");

        h312n.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        h312n.setForeground(new java.awt.Color(51, 255, 204));
        h312n.setText("Paneer Noodles");

        h312q.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel146.setBackground(new java.awt.Color(255, 255, 0));
        jLabel146.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel146.setForeground(new java.awt.Color(255, 255, 0));
        jLabel146.setText("₹");

        h312p.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        h312p.setForeground(new java.awt.Color(255, 255, 0));
        h312p.setText("89");

        h312.setBackground(new java.awt.Color(255, 102, 0));
        h312.setForeground(new java.awt.Color(255, 255, 255));
        h312.setText("Add to Cart");
        h312.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h312ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel143))
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel144, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(h312n, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(h312q, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel146, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(h312p)
                .addGap(26, 26, 26)
                .addComponent(h312))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel143)
                .addGap(10, 10, 10)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel144, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(h312n))
                .addGap(7, 7, 7)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(h312q, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel146)
                    .addComponent(h312p)
                    .addComponent(h312)))
        );

        jPanel_Home.add(jPanel36);
        jPanel36.setBounds(60, 120, 240, 190);

        jLabel67.setBackground(new java.awt.Color(204, 255, 255));
        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 102, 0));
        jLabel67.setText("!!! Deal Of The Day !!!");
        jPanel_Home.add(jLabel67);
        jLabel67.setBounds(270, 40, 410, 44);

        ByHotel1.setBackground(new java.awt.Color(102, 102, 102));
        ByHotel1.setForeground(new java.awt.Color(255, 255, 255));
        ByHotel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout ByHotel1Layout = new javax.swing.GroupLayout(ByHotel1);
        ByHotel1.setLayout(ByHotel1Layout);
        ByHotel1Layout.setHorizontalGroup(
            ByHotel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        ByHotel1Layout.setVerticalGroup(
            ByHotel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel_Home.add(ByHotel1);
        ByHotel1.setBounds(130, 330, 280, 240);

        ByCatogory1.setBackground(new java.awt.Color(102, 102, 102));
        ByCatogory1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout ByCatogory1Layout = new javax.swing.GroupLayout(ByCatogory1);
        ByCatogory1.setLayout(ByCatogory1Layout);
        ByCatogory1Layout.setHorizontalGroup(
            ByCatogory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        ByCatogory1Layout.setVerticalGroup(
            ByCatogory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel_Home.add(ByCatogory1);
        ByCatogory1.setBounds(560, 330, 270, 240);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255,165));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel_Home.add(jPanel6);
        jPanel6.setBounds(240, 40, 440, 50);

        jLabel9.setBackground(new java.awt.Color(53, 53, 53,160));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home_background.png"))); // NOI18N
        jPanel_Home.add(jLabel9);
        jLabel9.setBounds(10, 0, 1000, 610);

        jTabbedPane1.addTab("tab1", jPanel_Home);

        jPanel_Profile.setBackground(new java.awt.Color(240, 239, 235));
        jPanel_Profile.setForeground(new java.awt.Color(39, 125, 161));
        jPanel_Profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 204));
        jPanel2.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Profile");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 10, 102, 29);

        jPanel_Profile.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 29, 1000, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Address:");
        jPanel_Profile.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        fname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fname.setForeground(new java.awt.Color(230, 57, 70));
        fname.setText("Fname");
        jPanel_Profile.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 270, -1));

        lname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lname.setForeground(new java.awt.Color(230, 57, 70));
        jPanel_Profile.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 260, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("User name:");
        jPanel_Profile.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Phone Number:");
        jPanel_Profile.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Mail ID:");
        jPanel_Profile.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("D.O.B :");
        jPanel_Profile.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uname.setForeground(new java.awt.Color(39, 125, 161));
        jPanel_Profile.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 290, -1));

        phone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(39, 125, 161));
        jPanel_Profile.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 250, -1));

        mail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mail.setForeground(new java.awt.Color(39, 125, 161));
        jPanel_Profile.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 270, 500, -1));

        bdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bdate.setForeground(new java.awt.Color(39, 125, 161));
        jPanel_Profile.add(bdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 160, -1));

        jButton_editProfile.setBackground(new java.awt.Color(20, 33, 61));
        jButton_editProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_editProfile.setForeground(new java.awt.Color(255, 255, 204));
        jButton_editProfile.setText("Edit Profile");
        jButton_editProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_editProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editProfileActionPerformed(evt);
            }
        });
        jPanel_Profile.add(jButton_editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 190, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("G:\\FALL SEMESTER 2020-21\\JAVA\\PROJECT\\Images and icons\\Prof.png")); // NOI18N
        jPanel_Profile.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jScrollPane1.setBorder(null);

        address.setBackground(new java.awt.Color(240, 239, 235));
        address.setColumns(20);
        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(39, 125, 161));
        address.setRows(5);
        address.setBorder(null);
        address.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(address);

        jPanel_Profile.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 430, 180));

        jTabbedPane1.addTab("tab2", jPanel_Profile);

        jPanel_Cart.setBackground(new java.awt.Color(255, 204, 102));
        jPanel_Cart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartTable.setBackground(new java.awt.Color(204, 255, 255));
        cartTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S. No:", "Date and time", "cart ID", "food name", "quantity", "price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cartTable.setGridColor(new java.awt.Color(255, 153, 0));
        cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cartTable);
        if (cartTable.getColumnModel().getColumnCount() > 0) {
            cartTable.getColumnModel().getColumn(0).setPreferredWidth(4);
            cartTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            cartTable.getColumnModel().getColumn(2).setPreferredWidth(4);
            cartTable.getColumnModel().getColumn(3).setPreferredWidth(200);
            cartTable.getColumnModel().getColumn(4).setPreferredWidth(4);
            cartTable.getColumnModel().getColumn(5).setPreferredWidth(4);
            cartTable.getColumnModel().getColumn(6).setPreferredWidth(4);
        }

        jPanel_Cart.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 710, 400));

        jPanel4.setBackground(new java.awt.Color(163, 52, 209));

        jButton_placeOrder.setBackground(new java.awt.Color(255, 51, 0));
        jButton_placeOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_placeOrder.setForeground(new java.awt.Color(255, 255, 255));
        jButton_placeOrder.setText("Place Order");
        jButton_placeOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_placeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_placeOrderActionPerformed(evt);
            }
        });

        jLabel_TOTAL.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jLabel_TOTAL.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TOTAL.setText("00000");

        jLabel36.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("TOTAL:₹");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Cart List");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_placeOrder)
                .addGap(61, 61, 61))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel_TOTAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton_placeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jPanel_Cart.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1000, 40));

        jLabel_fn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_fn.setText("Food name:");
        jPanel_Cart.add(jLabel_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 90, -1));

        jLabel_foodName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_foodName.setForeground(new java.awt.Color(255, 0, 0));
        jPanel_Cart.add(jLabel_foodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 220, -1));

        jLabel_q.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_q.setText("Quantity:");
        jPanel_Cart.add(jLabel_q, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 70, 20));

        jLabel_quantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_quantity.setForeground(new java.awt.Color(255, 0, 0));
        jPanel_Cart.add(jLabel_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, -1, 20));

        jLabel_p.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_p.setText("Price:");
        jPanel_Cart.add(jLabel_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, -1, -1));

        jLabel_t.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_t.setText("Total:");
        jPanel_Cart.add(jLabel_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, -1, -1));

        jLabel_price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_price.setForeground(new java.awt.Color(255, 0, 0));
        jPanel_Cart.add(jLabel_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, -1, 20));

        jLabel_total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_total.setForeground(new java.awt.Color(255, 0, 0));
        jPanel_Cart.add(jLabel_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, 20));

        jButton_remove.setBackground(new java.awt.Color(204, 0, 0));
        jButton_remove.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton_remove.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remove.setText("Remove");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });
        jPanel_Cart.add(jButton_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 80, 30));

        jLabel_Cid.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel_Cid.setForeground(new java.awt.Color(102, 102, 102));
        jPanel_Cart.add(jLabel_Cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 30, -1));

        jLabel_cid.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel_cid.setText("Cart ID:");
        jPanel_Cart.add(jLabel_cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("!!  Tap the food item");
        jPanel_Cart.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 180, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("to select and edit or remove !!");
        jPanel_Cart.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, -1, -1));

        jButton_change.setBackground(new java.awt.Color(0, 204, 51));
        jButton_change.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton_change.setForeground(new java.awt.Color(255, 255, 255));
        jButton_change.setText("Change");
        jButton_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_changeActionPerformed(evt);
            }
        });
        jPanel_Cart.add(jButton_change, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 70, 20));

        jSpinner_Q.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel_Cart.add(jSpinner_Q, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 40, -1));

        jTabbedPane1.addTab("tab3", jPanel_Cart);

        jPanel_Order.setBackground(new java.awt.Color(0, 204, 102));
        jPanel_Order.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Orders");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(880, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel_Order.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1060, 40));

        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        OrderTable.setBackground(new java.awt.Color(255, 204, 204));
        OrderTable.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SI No:", "Date and Time", "Order ID", "Items", "Shipping Address", "Mode Of Payment", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OrderTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OrderTable.setGridColor(new java.awt.Color(0, 153, 0));
        OrderTable.setSelectionBackground(new java.awt.Color(0, 204, 0));
        OrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(OrderTable);
        if (OrderTable.getColumnModel().getColumnCount() > 0) {
            OrderTable.getColumnModel().getColumn(0).setPreferredWidth(4);
            OrderTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            OrderTable.getColumnModel().getColumn(2).setPreferredWidth(4);
            OrderTable.getColumnModel().getColumn(3).setPreferredWidth(4);
            OrderTable.getColumnModel().getColumn(4).setPreferredWidth(200);
            OrderTable.getColumnModel().getColumn(5).setPreferredWidth(180);
            OrderTable.getColumnModel().getColumn(6).setPreferredWidth(4);
        }

        jPanel_Order.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 310));

        jTabbedPane1.addTab("tab4", jPanel_Order);

        jPanel_About.setBackground(new java.awt.Color(51, 51, 0));
        jPanel_About.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setBackground(new java.awt.Color(0, 0, 0));
        jLabel41.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 0));
        jLabel41.setText("About Us");
        jPanel_About.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("1.The project FOODZ was developed to make the customer reach their loved food within 30 - 40 minutes from their\nsurrounding hotels for a minimal and reasonable cost.\n\n2.The project was developed with no profit intent and just to make the project reach to the best of customers \nsatisfaction.\n\n3.Project FOODZ is a purely In-Home developed project.\n\n4.The project was developed using JAVA programming language.\n\n5.Mail us at : foodz.customercare@gmail.com\n");
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane5.setViewportView(jTextArea1);

        jPanel_About.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 970, 330));

        jLabel42.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 255, 255));
        jLabel42.setText("   FOLLOW US ON:");
        jPanel_About.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 150, 30));

        jLabel_twitter.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/twiter_1.jpg"))); // NOI18N
        jLabel_twitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_twitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_twitterMouseClicked(evt);
            }
        });
        jPanel_About.add(jLabel_twitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 60, 50));

        jLabel_facebook.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/facebook2.jpg"))); // NOI18N
        jLabel_facebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_facebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_facebookMouseClicked(evt);
            }
        });
        jPanel_About.add(jLabel_facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 60, 50));

        jLabel_instagram.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/insta1.jpg"))); // NOI18N
        jLabel_instagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_instagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_instagramMouseClicked(evt);
            }
        });
        jPanel_About.add(jLabel_instagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, 60, 50));

        jTabbedPane1.addTab("tab5", jPanel_About);

        jPanel_OrderItems.setBackground(new java.awt.Color(202, 255, 191));
        jPanel_OrderItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(189, 178, 255));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Orders Items List");

        BackButton_OL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        BackButton_OL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton_OL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButton_OLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BackButton_OL)
                .addGap(27, 27, 27)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(760, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(BackButton_OL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_OrderItems.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1060, 40));

        jLabel_OID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_OID.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_OID.setText("0000");
        jPanel_OrderItems.add(jLabel_OID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Order ID:");
        jPanel_OrderItems.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 30));

        jTable_OrderList.setBackground(new java.awt.Color(0, 0, 0));
        jTable_OrderList.setForeground(new java.awt.Color(255, 255, 255));
        jTable_OrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SI No:", "Food Name", "Quantity", "Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_OrderList.setGridColor(new java.awt.Color(255, 0, 0));
        jTable_OrderList.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jTable_OrderList);
        if (jTable_OrderList.getColumnModel().getColumnCount() > 0) {
            jTable_OrderList.getColumnModel().getColumn(0).setPreferredWidth(4);
            jTable_OrderList.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable_OrderList.getColumnModel().getColumn(2).setPreferredWidth(4);
            jTable_OrderList.getColumnModel().getColumn(3).setPreferredWidth(4);
            jTable_OrderList.getColumnModel().getColumn(4).setPreferredWidth(4);
        }

        jPanel_OrderItems.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 760, 300));

        jLabel_Ototal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Ototal.setForeground(new java.awt.Color(153, 0, 153));
        jLabel_Ototal.setText("000000");
        jPanel_OrderItems.add(jLabel_Ototal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, -1, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("TOTAL : ₹");
        jPanel_OrderItems.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 70, 20));

        jTabbedPane1.addTab("tab4", jPanel_OrderItems);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 1000, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void update_carttable(){
        jLabel_cid.setVisible(false);
        jLabel_fn.setVisible(false);
        jLabel_q.setVisible(false);
        jLabel_p.setVisible(false);
        jLabel_t.setVisible(false);
        jButton_remove.setVisible(false);
        jSpinner_Q.setVisible(false);
        jButton_change.setVisible(false);
        try {
            PreparedStatement ps;
        ResultSet rs;
        String U_id = id.getText();
        
        String query = "SELECT * FROM `cart_list` WHERE `u_id` =?";
        
            ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, U_id);
            
            rs = ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)cartTable.getModel();
            tm.setRowCount(0);
            int i=1;
            while(rs.next())
            {
                    Object o[]={i,rs.getString(3),rs.getString(1),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
                    tm.addRow(o);
                    i++;
            }
            jLabel_Cid.setText("");
                jLabel_foodName.setText("");
                jLabel_quantity.setText("");
                jLabel_price.setText("");
                jLabel_total.setText("");
                int sum=0;
                for(int j=0;j<cartTable.getRowCount();j++){
                    sum+=Integer.parseInt(cartTable.getValueAt(j, 6).toString());
                }
                jLabel_TOTAL.setText(Integer.toString(sum));
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void update_ordertable(){
        try {
            PreparedStatement ps;
        ResultSet rs;
        String U_id = id.getText();
        
        String query = "SELECT * FROM `order_list` WHERE `u_id` =?";
        
            ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, U_id);
            
            rs = ps.executeQuery();
            DefaultTableModel o_tm=(DefaultTableModel)OrderTable.getModel();
            o_tm.setRowCount(0);
            int i=1;
            while(rs.next())
            {
                    Object o[]={i,rs.getString(3),rs.getString(1),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
                    o_tm.addRow(o);
                    i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        if(evt.getSource()==Home){
            jTabbedPane1.setSelectedComponent(jPanel_Home);
            ByCatogory1.setVisible(false);
            ByHotel1.setVisible(false);
        }
        if(evt.getSource()==Profile){
            jTabbedPane1.setSelectedComponent(jPanel_Profile);
            
            try {
            PreparedStatement ps;
        ResultSet rs;
        String U_id = id.getText();
        
        String query = "SELECT * FROM `the_app_users` WHERE `u_id` =?";
        
            ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, U_id);
            
            rs = ps.executeQuery();
           
            if(rs.next())
            {
                    fname.setText(rs.getString("u_fname"));
                    lname.setText(rs.getString("u_lname"));
                    uname.setText(rs.getString("u_uname"));
                    phone.setText(rs.getString("u_phone"));
                    mail.setText(rs.getString("u_mail"));
                    bdate.setText(rs.getString("u_bdate"));
                    address.setText(rs.getString("u_address"));
                    
            }
            else{
                    JOptionPane.showMessageDialog(null, "Somthing went wrong", "Error", 2);
                }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        if(evt.getSource()==Cart){
            jTabbedPane1.setSelectedComponent(jPanel_Cart);
            update_carttable();
            
        }
        if(evt.getSource()==Orders){
            jTabbedPane1.setSelectedComponent(jPanel_Order);
            update_ordertable();
        }
        if(evt.getSource()==About){
            jTabbedPane1.setSelectedComponent(jPanel_About);
        }
        if(evt.getSource()==Logout){
            Login lgf = new Login();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
            
        }
    }//GEN-LAST:event_mouseClicked

    private void N_mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_mouseExited
        if(evt.getSource()==Profile){
            Profile.setBackground(new Color(102,102,102));
        }
        if(evt.getSource()==Cart){
            Cart.setBackground(new Color(102,102,102));
        }
        if(evt.getSource()==Orders){
            Orders.setBackground(new Color(102,102,102));
        }
        if(evt.getSource()==About){
            About.setBackground(new Color(102,102,102));
        }
        if(evt.getSource()==Logout){
            Logout.setBackground(new Color(102,102,102));
        }
    }//GEN-LAST:event_N_mouseExited

    private void N_mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_mouseEntered
        if(evt.getSource()==Profile){
            Profile.setBackground(new Color(64,64,64));
        }
        if(evt.getSource()==Cart){
            Cart.setBackground(new Color(64,64,64));
        }
        if(evt.getSource()==Orders){
            Orders.setBackground(new Color(64,64,64));
        }
        if(evt.getSource()==About){
            About.setBackground(new Color(64,64,64));
        }
        if(evt.getSource()==Logout){
            Logout.setBackground(new Color(64,64,64));
        }
    }//GEN-LAST:event_N_mouseEntered

    private void HomeBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBarMousePressed
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_HomeBarMousePressed

    private void HomeBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBarMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_HomeBarMouseDragged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButton_editProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editProfileActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        ByCatogory1.setVisible(false);
        ByHotel1.setVisible(false);
        Edit_profile epf = new Edit_profile();
        epf.setVisible(true);
        epf.pack();
        epf.setLocationRelativeTo(null);
        try {
            PreparedStatement ps;
        ResultSet rs;
        String U_id = id.getText();
        
        String query = "SELECT * FROM `the_app_users` WHERE `u_id` =?";
        
            ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, U_id);
            
            rs = ps.executeQuery();
           
            if(rs.next())
            {
                    epf.e_fname.setText(rs.getString("u_fname"));
                    epf.e_lname.setText(rs.getString("u_lname"));
                    epf.e_phone.setText(rs.getString("u_phone"));
                    epf.e_mail.setText(rs.getString("u_mail"));
                    epf.e_address.setText(rs.getString("u_address"));
                    epf.ep_uid.setText(rs.getString("u_id"));
                    }
            else{
                    JOptionPane.showMessageDialog(null, "Somthing went wrong", "Error", 2);
                }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_editProfileActionPerformed

    private void home_mouseEnterd(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_mouseEnterd
        Home.setBackground(new Color(64,64,64));
    }//GEN-LAST:event_home_mouseEnterd

    private void home_mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_mouseExited
        Home.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_home_mouseExited

    private void ByHotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ByHotelMouseClicked
                    String ID=id.getText();
                    ByRestaurant brt = new ByRestaurant();
                    brt.setVisible(true);
                    brt.pack();
                    brt.setLocationRelativeTo(null);
                    brt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    brt.id.setText(ID);
    }//GEN-LAST:event_ByHotelMouseClicked

    private void ByCatogoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ByCatogoryMouseClicked
        String ID=id.getText();
                    ByCategory bcy = new ByCategory();
                    bcy.setVisible(true);
                    bcy.pack();
                    bcy.setLocationRelativeTo(null);
                    bcy.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    bcy.id.setText(ID);
    }//GEN-LAST:event_ByCatogoryMouseClicked

    private void cartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartTableMouseClicked
        jLabel_cid.setVisible(true);
        jLabel_fn.setVisible(true);
        jLabel_q.setVisible(true);
        jLabel_p.setVisible(true);
        jLabel_t.setVisible(true);
        jButton_remove.setVisible(true);
        jSpinner_Q.setVisible(true);
        jButton_change.setVisible(true);
        jSpinner_Q.setValue(1);
        try {
            int row=cartTable.getSelectedRow();
            String table_click=(cartTable.getModel().getValueAt(row,2).toString());
            PreparedStatement ps;
            ResultSet rs;
        
            String query = "SELECT * FROM `cart_list` WHERE `c_id` ="+table_click;
            ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            if(rs.next()){
                jLabel_Cid.setText(rs.getString("c_id"));
                jLabel_foodName.setText(rs.getString("food_name"));
                jLabel_quantity.setText(rs.getString("quantity"));
                jLabel_price.setText(rs.getString("price"));
                jLabel_total.setText(rs.getString("total"));
            }
            else{
                    JOptionPane.showMessageDialog(null, "Somthing went wrong", "Error", 2);
                }
            } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cartTableMouseClicked

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
        try {
            PreparedStatement ps;
        
            String query = "DELETE FROM `cart_list` WHERE `c_id` ="+jLabel_Cid.getText();
            ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Food item is REMOVED\nfrom the cart list successfully ");
            update_carttable();
            } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jButton_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_changeActionPerformed
        String q=jSpinner_Q.getValue().toString(),p=jLabel_price.getText();
        update_cart(q,p);
    }//GEN-LAST:event_jButton_changeActionPerformed

    private void jButton_placeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_placeOrderActionPerformed
        String t=jLabel_TOTAL.getText();
        if(t.equals("0")){
            JOptionPane.showMessageDialog(null, "Your Cart List is EMPLTY", "Error", 2);
        }
        else{
            jTabbedPane1.setSelectedIndex(0);
            ByCatogory1.setVisible(false);
        ByHotel1.setVisible(false);
        ConfirmOrder cfo = new ConfirmOrder();
        cfo.setVisible(true);
        cfo.pack();
        cfo.setLocationRelativeTo(null);
        try {
            PreparedStatement ps;
        ResultSet rs;
        String U_id = id.getText();
        
        String query = "SELECT * FROM `the_app_users` WHERE `u_id` =?";
        
            ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, U_id);
            
            rs = ps.executeQuery();
           
            if(rs.next())
            {
                    cfo.jTextArea_Address.setText(rs.getString("u_address"));
                    cfo.ep_uid.setText(rs.getString("u_id"));
                    cfo.jLabel_TOTAL.setText(jLabel_TOTAL.getText());
                    }
            else{
                    JOptionPane.showMessageDialog(null, "Somthing went wrong", "Error", 2);
                }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton_placeOrderActionPerformed

    private void OrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderTableMouseClicked
        jTabbedPane1.setSelectedComponent(jPanel_OrderItems);
        try {
            int row=OrderTable.getSelectedRow();
            String table_click=(OrderTable.getModel().getValueAt(row,2).toString());
            PreparedStatement ps;
            ResultSet rs;
        
            String query = "SELECT * FROM `order_items_list` WHERE `o_id` ="+table_click;
            ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            DefaultTableModel ol_tm=(DefaultTableModel)jTable_OrderList.getModel();
            ol_tm.setRowCount(0);
            int i=1;
            while(rs.next())
            {
                    Object o[]={i,rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
                    ol_tm.addRow(o);
                    i++;
            }
            int sum=0;
            for(int j=0;j<jTable_OrderList.getRowCount();j++){
                    sum+=Integer.parseInt(jTable_OrderList.getValueAt(j, 4).toString());
                }
                jLabel_Ototal.setText(Integer.toString(sum));
                jLabel_OID.setText(table_click);
            } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OrderTableMouseClicked

    private void BackButton_OLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton_OLMouseClicked
        jTabbedPane1.setSelectedComponent(jPanel_Order);
    }//GEN-LAST:event_BackButton_OLMouseClicked

    private void h56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h56ActionPerformed
        String n=h56n.getText(),p=h56p.getText(),q=h56q.getValue().toString();
        addcart(n,q,p);
    }//GEN-LAST:event_h56ActionPerformed

    private void h21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h21ActionPerformed
        /*2*/ String n=h21n.getText(),p=h21p.getText(),q=h21q.getValue().toString();
        addcart(n,q,p);
    }//GEN-LAST:event_h21ActionPerformed

    private void h312ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h312ActionPerformed
        String n=h312n.getText(),p=h312p.getText(),q=h312q.getValue().toString();
        addcart(n,q,p);
    }//GEN-LAST:event_h312ActionPerformed

    private void ByCatogoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ByCatogoryMouseEntered
        ByCatogory1.setVisible(true);
    }//GEN-LAST:event_ByCatogoryMouseEntered

    private void ByHotelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ByHotelMouseEntered
        ByHotel1.setVisible(true);
    }//GEN-LAST:event_ByHotelMouseEntered

    private void ByHotelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ByHotelMouseExited
        ByHotel1.setVisible(false);
    }//GEN-LAST:event_ByHotelMouseExited

    private void ByCatogoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ByCatogoryMouseExited
        ByCatogory1.setVisible(false);
    }//GEN-LAST:event_ByCatogoryMouseExited

    private void jLabel_twitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_twitterMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()>0){
            if(Desktop.isDesktopSupported()){
                Desktop desktop=Desktop.getDesktop();
                try{
                    URI uri=new URI("www.twitter.com");
                    desktop.browse(uri);
                }catch (IOException ex){
                        ex.getMessage();
                }
                catch (URISyntaxException ex){
                        ex.getMessage();
                }
            }
        }
    }//GEN-LAST:event_jLabel_twitterMouseClicked

    private void jLabel_facebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_facebookMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()>0){
            if(Desktop.isDesktopSupported()){
                Desktop desktop=Desktop.getDesktop();
                try{
                    URI uri=new URI("www.facebook.com");
                    desktop.browse(uri);
                }catch (IOException ex){
                      ex.getMessage();
                }
                catch (URISyntaxException ex){
                       ex.getMessage();
                }
            }
        }
    }//GEN-LAST:event_jLabel_facebookMouseClicked

    private void jLabel_instagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_instagramMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()>0){
            if(Desktop.isDesktopSupported()){
                Desktop desktop=Desktop.getDesktop();
                try{
                    URI uri=new URI("www.instagram.com");
                    desktop.browse(uri);
                }catch (IOException ex){
                     ex.getMessage();
                }
                catch (URISyntaxException ex){
                    ex.getMessage();
                }
            }
        }
    }//GEN-LAST:event_jLabel_instagramMouseClicked
    public  void addcart(String n,String q, String p){
        int total = Integer.parseInt(q)*Integer.parseInt(p);
        String t=Integer.toString(total);
        PreparedStatement ps;
        String query = "INSERT INTO `cart_list`(`u_id`, `food_name`, `quantity`, `price`, `total`) VALUES (?,?,?,?,?)";
            
            try {
                ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, id.getText());
                ps.setString(2, n);
                ps.setString(3, q);
                ps.setString(4, p);
                ps.setString(5, t);
                
                if(ps.executeUpdate() > 0)
                {
                    Icon icon=new javax.swing.ImageIcon(getClass().getResource("/icons/success.png"));
        JOptionPane.showMessageDialog(null,"Food name: "+n+"\nPrice: "+p+"\nQuantity: "+q+"\nTotal = "+t, "!!Added to cart successfully!!", JOptionPane.INFORMATION_MESSAGE,icon);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Somthing went wrong", "Error",2);
                }
                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }
    public  void update_cart(String q, String p){
        int total = Integer.parseInt(q)*Integer.parseInt(p);
        String t=Integer.toString(total);
        PreparedStatement ps;
        String query = "UPDATE `cart_list` SET `quantity`=?,`total`=? WHERE `c_id`="+jLabel_Cid.getText();
            
            try {
                ps = (PreparedStatement) MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, q);
                ps.setString(2, t);
                
                if(ps.executeUpdate() > 0)
                {
                    Icon icon=new javax.swing.ImageIcon(getClass().getResource("/icons/success.png"));
        JOptionPane.showMessageDialog(null,"Food name: "+jLabel_foodName.getText()+"\nPrice: "+p+"\nQuantity: "+q+"\nTotal = "+t, "!!Cart updated successfully!!", JOptionPane.INFORMATION_MESSAGE,icon);
                   update_carttable();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Somthing went wrong", "Error",2);
                }
                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JLabel BackButton_OL;
    private javax.swing.JPanel ByCatogory;
    protected javax.swing.JPanel ByCatogory1;
    private javax.swing.JPanel ByHotel;
    protected javax.swing.JPanel ByHotel1;
    private javax.swing.JPanel Cart;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel HomeBar;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel Navigation;
    private javax.swing.JTable OrderTable;
    private javax.swing.JPanel Orders;
    private javax.swing.JPanel Profile;
    private javax.swing.JTextArea address;
    private javax.swing.JLabel bdate;
    private javax.swing.JTable cartTable;
    private javax.swing.JLabel fname;
    private javax.swing.JButton h21;
    private javax.swing.JLabel h21n;
    private javax.swing.JLabel h21p;
    private javax.swing.JSpinner h21q;
    private javax.swing.JButton h312;
    private javax.swing.JLabel h312n;
    private javax.swing.JLabel h312p;
    private javax.swing.JSpinner h312q;
    private javax.swing.JButton h56;
    private javax.swing.JLabel h56n;
    private javax.swing.JLabel h56p;
    private javax.swing.JSpinner h56q;
    protected javax.swing.JLabel id;
    private javax.swing.JButton jButton_change;
    private javax.swing.JButton jButton_editProfile;
    private javax.swing.JButton jButton_placeOrder;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel299;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel300;
    private javax.swing.JLabel jLabel302;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel402;
    private javax.swing.JLabel jLabel403;
    private javax.swing.JLabel jLabel405;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabel_Cid;
    private javax.swing.JLabel jLabel_OID;
    private javax.swing.JLabel jLabel_Ototal;
    private javax.swing.JLabel jLabel_TOTAL;
    private javax.swing.JLabel jLabel_cid;
    private javax.swing.JLabel jLabel_facebook;
    private javax.swing.JLabel jLabel_fn;
    private javax.swing.JLabel jLabel_foodName;
    private javax.swing.JLabel jLabel_instagram;
    private javax.swing.JLabel jLabel_p;
    private javax.swing.JLabel jLabel_price;
    private javax.swing.JLabel jLabel_q;
    private javax.swing.JLabel jLabel_quantity;
    private javax.swing.JLabel jLabel_t;
    private javax.swing.JLabel jLabel_total;
    private javax.swing.JLabel jLabel_twitter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel93;
    private javax.swing.JPanel jPanel_About;
    private javax.swing.JPanel jPanel_Cart;
    private javax.swing.JPanel jPanel_Home;
    private javax.swing.JPanel jPanel_Order;
    private javax.swing.JPanel jPanel_OrderItems;
    private javax.swing.JPanel jPanel_Profile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner_Q;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_OrderList;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel uname;
    // End of variables declaration//GEN-END:variables
}
